import type { Application, CalendarEvent } from "./types"

export const mockApplications: Application[] = [
  {
    id: "app-1",
    jobId: "job-1",
    jobTitle: "Senior Frontend Engineer",
    company: { name: "Stripe", logo: "S" },
    score: 94,
    status: "interview",
    submittedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    daysInStage: 3,
    interviewDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    interviewProbability: 85,
  },
  {
    id: "app-2",
    jobId: "job-2",
    jobTitle: "Staff Engineer",
    company: { name: "Vercel", logo: "V" },
    score: 91,
    status: "screening",
    submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    daysInStage: 2,
    interviewProbability: 72,
  },
  {
    id: "app-3",
    jobId: "job-3",
    jobTitle: "Engineering Manager",
    company: { name: "Linear", logo: "L" },
    score: 88,
    status: "applied",
    submittedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    daysInStage: 3,
    interviewProbability: 65,
  },
  {
    id: "app-4",
    jobId: "job-4",
    jobTitle: "Principal Engineer",
    company: { name: "Notion", logo: "N" },
    score: 85,
    status: "in_review",
    lastActivityAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    daysInStage: 1,
  },
  {
    id: "app-5",
    jobId: "job-5",
    jobTitle: "Senior Software Engineer",
    company: { name: "Figma", logo: "F" },
    score: 82,
    status: "scored",
    lastActivityAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    daysInStage: 0,
  },
  {
    id: "app-6",
    jobId: "job-6",
    jobTitle: "Tech Lead",
    company: { name: "Airbnb", logo: "A" },
    score: 79,
    status: "discovered",
    lastActivityAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    daysInStage: 0,
  },
  {
    id: "app-7",
    jobId: "job-7",
    jobTitle: "Senior Engineer",
    company: { name: "Spotify", logo: "Sp" },
    score: 76,
    status: "rejected",
    submittedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    daysInStage: 2,
  },
  {
    id: "app-8",
    jobId: "job-8",
    jobTitle: "Frontend Lead",
    company: { name: "Discord", logo: "D" },
    score: 87,
    status: "offer",
    submittedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    daysInStage: 1,
  },
  {
    id: "app-9",
    jobId: "job-9",
    jobTitle: "Software Engineer",
    company: { name: "Slack", logo: "Sl" },
    score: 73,
    status: "ghosted",
    submittedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    daysInStage: 14,
  },
  {
    id: "app-10",
    jobId: "job-10",
    jobTitle: "Senior React Developer",
    company: { name: "GitHub", logo: "GH" },
    score: 90,
    status: "interview",
    submittedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    daysInStage: 1,
    interviewDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    interviewProbability: 90,
  },
  {
    id: "app-11",
    jobId: "job-11",
    jobTitle: "Platform Engineer",
    company: { name: "Cloudflare", logo: "CF" },
    score: 81,
    status: "withdrawn",
    submittedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    daysInStage: 1,
  },
  {
    id: "app-12",
    jobId: "job-12",
    jobTitle: "Full Stack Engineer",
    company: { name: "Supabase", logo: "Su" },
    score: 86,
    status: "applied",
    submittedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    daysInStage: 2,
    interviewProbability: 60,
  },
]

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "event-1",
    applicationId: "app-1",
    type: "interview",
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    title: "Technical Interview",
    company: "Stripe",
  },
  {
    id: "event-2",
    applicationId: "app-10",
    type: "interview",
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    title: "Final Round",
    company: "GitHub",
  },
  {
    id: "event-3",
    applicationId: "app-3",
    type: "follow_up",
    date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    title: "Follow-up Email",
    company: "Linear",
  },
  {
    id: "event-4",
    applicationId: "app-8",
    type: "deadline",
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    title: "Offer Deadline",
    company: "Discord",
  },
  {
    id: "event-5",
    applicationId: "app-1",
    type: "submitted",
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    title: "Application Submitted",
    company: "Stripe",
  },
  {
    id: "event-6",
    applicationId: "app-2",
    type: "submitted",
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    title: "Application Submitted",
    company: "Vercel",
  },
]
