import type { Application, CalendarEvent } from "./types"

// 20 applications across 8 statuses as per spec:
// Pending (3), Submitted (5), Screening (4), Interview (3), Offer (1), Rejected (2), Withdrawn (1), Ghosted (1)
export const mockApplications: Application[] = [
  // PENDING (3)
  {
    id: "app-1",
    jobId: "job-1",
    jobTitle: "Senior Frontend Engineer",
    company: { name: "Stripe", logo: "S" },
    score: 94,
    status: "pending",
    lastActivityAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    daysInStage: 0,
    interviewProbability: 85,
    source: "LinkedIn",
  },
  {
    id: "app-2",
    jobId: "job-2",
    jobTitle: "Staff Engineer",
    company: { name: "Vercel", logo: "V" },
    score: 91,
    status: "pending",
    lastActivityAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    daysInStage: 0,
    interviewProbability: 78,
    source: "Company Website",
  },
  {
    id: "app-3",
    jobId: "job-3",
    jobTitle: "Engineering Manager",
    company: { name: "Linear", logo: "L" },
    score: 88,
    status: "pending",
    lastActivityAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    daysInStage: 0,
    interviewProbability: 72,
    source: "Referral",
  },

  // SUBMITTED (5)
  {
    id: "app-4",
    jobId: "job-4",
    jobTitle: "Principal Engineer",
    company: { name: "Notion", logo: "N" },
    score: 85,
    status: "submitted",
    submittedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    daysInStage: 2,
    interviewProbability: 65,
    source: "Greenhouse",
  },
  {
    id: "app-5",
    jobId: "job-5",
    jobTitle: "Senior Software Engineer",
    company: { name: "Figma", logo: "F" },
    score: 82,
    status: "submitted",
    submittedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    daysInStage: 3,
    interviewProbability: 60,
    source: "Lever",
  },
  {
    id: "app-6",
    jobId: "job-6",
    jobTitle: "Tech Lead",
    company: { name: "Airbnb", logo: "A" },
    score: 79,
    status: "submitted",
    submittedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    daysInStage: 1,
    interviewProbability: 55,
    source: "LinkedIn Easy Apply",
  },
  {
    id: "app-7",
    jobId: "job-7",
    jobTitle: "Full Stack Engineer",
    company: { name: "Supabase", logo: "Su" },
    score: 86,
    status: "submitted",
    submittedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    daysInStage: 4,
    interviewProbability: 68,
    source: "Ashby",
  },
  {
    id: "app-8",
    jobId: "job-8",
    jobTitle: "Software Architect",
    company: { name: "Datadog", logo: "D" },
    score: 77,
    status: "submitted",
    submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    daysInStage: 5,
    interviewProbability: 50,
    source: "Company Website",
  },

  // SCREENING (4)
  {
    id: "app-9",
    jobId: "job-9",
    jobTitle: "Frontend Architect",
    company: { name: "Shopify", logo: "Sh" },
    score: 90,
    status: "screening",
    submittedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    daysInStage: 2,
    interviewProbability: 75,
    source: "Greenhouse",
  },
  {
    id: "app-10",
    jobId: "job-10",
    jobTitle: "Lead Engineer",
    company: { name: "Plaid", logo: "P" },
    score: 87,
    status: "screening",
    submittedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    daysInStage: 3,
    interviewProbability: 70,
    source: "Lever",
  },
  {
    id: "app-11",
    jobId: "job-11",
    jobTitle: "Staff Software Engineer",
    company: { name: "Twilio", logo: "T" },
    score: 83,
    status: "screening",
    submittedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    daysInStage: 4,
    interviewProbability: 65,
    source: "Workday",
  },
  {
    id: "app-12",
    jobId: "job-12",
    jobTitle: "Senior Platform Engineer",
    company: { name: "Cloudflare", logo: "CF" },
    score: 81,
    status: "screening",
    submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    daysInStage: 1,
    interviewProbability: 62,
    source: "Company Website",
  },

  // INTERVIEW (3)
  {
    id: "app-13",
    jobId: "job-13",
    jobTitle: "Senior React Developer",
    company: { name: "GitHub", logo: "GH" },
    score: 92,
    status: "interview",
    submittedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    daysInStage: 2,
    interviewDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    interviewProbability: 90,
    source: "Referral",
  },
  {
    id: "app-14",
    jobId: "job-14",
    jobTitle: "Frontend Lead",
    company: { name: "Atlassian", logo: "At" },
    score: 88,
    status: "interview",
    submittedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    daysInStage: 5,
    interviewDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    interviewProbability: 85,
    source: "LinkedIn",
  },
  {
    id: "app-15",
    jobId: "job-15",
    jobTitle: "Engineering Manager",
    company: { name: "Dropbox", logo: "Db" },
    score: 84,
    status: "interview",
    submittedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    daysInStage: 3,
    interviewDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    interviewProbability: 80,
    source: "Greenhouse",
  },

  // OFFER (1)
  {
    id: "app-16",
    jobId: "job-16",
    jobTitle: "Frontend Lead",
    company: { name: "Discord", logo: "Dc" },
    score: 93,
    status: "offer",
    submittedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    daysInStage: 1,
    source: "Company Website",
  },

  // REJECTED (2)
  {
    id: "app-17",
    jobId: "job-17",
    jobTitle: "Senior Engineer",
    company: { name: "Spotify", logo: "Sp" },
    score: 76,
    status: "rejected",
    submittedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    daysInStage: 2,
    source: "LinkedIn Easy Apply",
  },
  {
    id: "app-18",
    jobId: "job-18",
    jobTitle: "Platform Engineer",
    company: { name: "Netflix", logo: "N" },
    score: 72,
    status: "rejected",
    submittedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    daysInStage: 4,
    source: "Lever",
  },

  // WITHDRAWN (1)
  {
    id: "app-19",
    jobId: "job-19",
    jobTitle: "Staff Engineer",
    company: { name: "Coinbase", logo: "Cb" },
    score: 80,
    status: "withdrawn",
    submittedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    daysInStage: 1,
    source: "Company Website",
  },

  // GHOSTED (1)
  {
    id: "app-20",
    jobId: "job-20",
    jobTitle: "Software Engineer",
    company: { name: "Slack", logo: "Sl" },
    score: 73,
    status: "ghosted",
    submittedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    lastActivityAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    daysInStage: 14,
    source: "Workday",
  },
]

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "event-1",
    applicationId: "app-13",
    type: "interview",
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    title: "Technical Interview",
    company: "GitHub",
  },
  {
    id: "event-2",
    applicationId: "app-14",
    type: "interview",
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    title: "Final Round",
    company: "Atlassian",
  },
  {
    id: "event-3",
    applicationId: "app-15",
    type: "interview",
    date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    title: "Hiring Manager Chat",
    company: "Dropbox",
  },
  {
    id: "event-4",
    applicationId: "app-16",
    type: "deadline",
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    title: "Offer Deadline",
    company: "Discord",
  },
  {
    id: "event-5",
    applicationId: "app-4",
    type: "submitted",
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    title: "Application Submitted",
    company: "Notion",
  },
  {
    id: "event-6",
    applicationId: "app-5",
    type: "submitted",
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    title: "Application Submitted",
    company: "Figma",
  },
  {
    id: "event-7",
    applicationId: "app-9",
    type: "follow_up",
    date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    title: "Send Follow-up",
    company: "Shopify",
  },
  {
    id: "event-8",
    applicationId: "app-1",
    type: "follow_up",
    date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    title: "Review Documents",
    company: "Stripe",
  },
]
